[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "cd server && npm ci --production"
]

[phases.build]
cmds = [
  "echo 'No build step needed for backend'"
]

[start]
cmd = "cd server && node index.js"
