[build]
builder = "NIXPACKS"
nixpacksConfigPath = "nixpacks.toml"
watchPatterns = ["**/*.js", "**/*.json"]

[deploy]
startCommand = "node index.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
healthcheckPath = "/api/posts"
healthcheckTimeout = 100
